name: Daily Check-in

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 0:00 执行一次

jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4

      - name: Run check-in script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          FROM_ADDRESS: ${{ secrets.FROM_ADDRESS }}
          ADDRESS_PASSWORD: ${{ secrets.ADDRESS_PASSWORD }}
          RECEIVER_ADDRESS: ${{ secrets.RECEIVER_ADDRESS }}
          COOKIE: ${{ secrets.COOKIE }}
        run: |
          python checkin.py
